### PR TITLE
proto: Ensure RenterFunds >= 5*BaseRPCPrice

### PR DESCRIPTION
**Pull request by lukechampine**
Fixes https://github.com/lukechampine/us/issues/80

### CODE REVIEW

**Comment by lukechampine** [comment]
Goober, test and merge

**Comment by jkawamoto** [comment]
I'm afraid that 5 is not enough. If I'm not mistaken, the host charges BaseRPCPrice if we lock a contract. That means, if we check the remaining fund 5 times, we use up the fund.  Even if locking a contract doesn't consume BaseRPCPrice, if we fail to renew the contract, we cannot renew the contract anymore. From my observations, it could happen frequently.

**Comment by lukechampine** [comment]
> If I'm not mistaken, the host charges BaseRPCPrice if we lock a contract

Locking does not require payment. You can see which RPCs require payment by grepping for `updateRevisionOutputs`. You'll see that in each case, the payment is now preceded by a `sufficientFunds` check.

**Comment by jkawamoto** [comment]
That's good to know, thanks.

So, even if we fail to renew a contract with `RenewAndClearContract: ReadResponse: consensus conflict: provided transaction set has prereqs, but is still invalid: transaction spends a nonexisting siacoin output`, we don't spend any coins. Is that correct?

**Comment by lukechampine** [comment]
Yep -- the new revision is only applied if the renewal transaction is accepted.

**Comment by jkawamoto** [comment]
Understand, thanks!

**Comment by jkawamoto** [comment]
We still get many `RenewAndClearContract: ReadResponse: communication error: rejected for low paying host valid output` errors. Do you have any idea why it still happens?

**Comment by lukechampine** [comment]
Hmm. I guess you should print out `s.host.BaseRPCPrice`, `finalPayment`, and `currentRevision.ValidRenterPayout()` to see what you're sending to the host. Perhaps this payment should add some leeway like `(Session).Write` does.

**Comment by jkawamoto** [comment]
I'd log them but how can I get the `finalPayment`? Is that the estimated cost?

**Comment by jkawamoto** [comment]
Interesting. Renewing a contract with this host https://siastats.info/hosts?=1674 fails with "RenewAndClearContract: ReadResponse: communication error: rejected for low paying host valid output" The host doesn't charge RPC calls and accessing a sector.

**Pull request merged**
